### ISSUE TITLE
Can't get app to start with config info

### ISSUE THREAD

**Issue by wrosko** [MRCIEU/MELODI-Presto#4]
I've been trying to re-implement MELODI and host on a personal machine accessible on my personal network, however I have no idea what I should put in the `config.py` which apparently needs to have a copy in the `create` directory?

https://github.com/MRCIEU/MELODI-Presto/blob/master/create/Creation.md

What would you recommend I put for these lines:
```

api_url='api url, e.g. https://www.some.thing/api/'
root_url='root url, e.g. https://www.some.thing/'

allowed_hosts="allowed hosts"
semmed_triple_total=total number of triples in predicate index
```

When I try to run, after doing the docker compose, I try to run `python create/create_semmed_freqs.py` but all I get are `elasticsearch.exceptions.ConnectionError` errors.

**Comment by elswob** [comment]
Hi. Apologies for the lack of documentation here. I've updated `Creation.md` to include some better information regarding how to set things up, and how `config.py` should look. There is also no need to create a copy of this in the `create` directory anymore.

I've also added notes on how to setup a local Elasticsearch instance.

Let me know if you need any more info.

**Comment by wrosko** [comment]
Hey, thanks so much! I'll give it a whirl tomorrow and will report back 😄

**Comment by wrosko** [comment]
Alright I've tried your updated code. I'm thinking there is a versioning issue or something similar?

I can't get the `melodi-presto-django` container running with the docker compose. I run into a sqlite version error:

```
melodi-presto-django |     backend = load_backend(db['ENGINE'])
melodi-presto-django |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 111, in load_backend
melodi-presto-django |     return import_module('%s.base' % backend_name)
melodi-presto-django |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
melodi-presto-django |     return _bootstrap._gcd_import(name[level:], package, level)
melodi-presto-django |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 73, i$
 <module>
melodi-presto-django |     check_sqlite_version()
melodi-presto-django |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 69, i$
 check_sqlite_version
melodi-presto-django |     'SQLite 3.9.0 or later is required (found %s).' % Database.sqlite_version
melodi-presto-django | django.core.exceptions.ImproperlyConfigured: SQLite 3.9.0 or later is required (found 3.8.7.1)
```




Edit: One moment, I forgot to rebuild I think

**Comment by wrosko** [comment]
Yup, I forgot to rebuild. Testing the rest of the stuff now.

**Comment by wrosko** [comment]
@elswob Sorry to be a bother, but still can't get this running. Containers start up fine. Having trouble with the indices. Indices have been names but cannot find location in codebase that sets the indices to the config names and so when running `create_semmed_freqs` with the py env active I get:

``` shell
python -m create.create_semmed_freqs
Creating counts for  semmeddb_triple
Running initial aggregation SUB_PRED_OBJ
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/projects/MELODI-Presto/create/create_semmed_freqs.py", line 119, in <module>
    create_counts("semmeddb_triple")
  File "/home/ubuntu/projects/MELODI-Presto/create/create_semmed_freqs.py", line 71, in create_counts
    for r in res["aggregations"]["my_buckets"]["buckets"]:
KeyError: 'aggregations'
```

And I expect the index to fail cause the counts weren't made, so running `index_semmed_predicate` yields the following but unsure if that's actually an error with the elastic index or something else:

``` shell
python -m create.index_semmeddb_predicate
2022-02-07 16:37:15 Indexing predicate data...
Creating index predicate_index
Creating index predicate_index
PUT http://localhost:9200/predicate_index [status:400 request:0.002s]
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/projects/MELODI-Presto/create/index_semmeddb_predicate.py", line 228, in <module>
    config.semmed_predicate_index,
  File "/home/ubuntu/projects/MELODI-Presto/create/index_semmeddb_predicate.py", line 97, in index_predicate_data
    create_index(index_name)
  File "/home/ubuntu/projects/MELODI-Presto/create/index_semmeddb_predicate.py", line 92, in create_index
    es.indices.create(index=index_name, body=request_body, request_timeout=timeout)
  File "/home/ubuntu/projects/MELODI-Presto/venv/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/ubuntu/projects/MELODI-Presto/venv/lib/python3.7/site-packages/elasticsearch/client/indices.py", line 91, in create
    params=params, body=body)
  File "/home/ubuntu/projects/MELODI-Presto/venv/lib/python3.7/site-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/home/ubuntu/projects/MELODI-Presto/venv/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 161, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/ubuntu/projects/MELODI-Presto/venv/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'The mapping definition cannot be nested under a type [_doc] unless include_type_name is set to true.')
```

Attempting the commented lines on the `freq` file:
``` shell
# initial query
# curl -X GET "localhost:9200/semmeddb/_search?pretty" -H 'Content-Type: application/json' -d '{ "aggs" : { "my_buckets" : { "composite": { "size":100, "sources": [{"sub-pred-obj":{"terms" : { "field" : "SUB_PRED_OBJ"}}} ] }}}} '

# after query
# curl -X GET "localhost:9200/semmeddb/_search?pretty" -H 'Content-Type: application/json' -d '{ "aggs" : { "my_buckets" : { "composite": { "size":100, "sources": [{"sub-pred-obj":{"terms" : { "field" : "SUB_PRED_OBJ"}}} ],"after":{"sub-pred-obj":"\"\"\"U\"\" lymphocyte\":LOCATION_OF:receptor"} }}}} '

# check
# curl -XGET 'localhost:9200/semmeddb/_search?pretty' -H 'Content-Type: application/json' -d '{"size":1,"query":{"bool":{"filter":[{"term":{"SUB_PRED_OBJ":"Encounter due to counseling:PROCESS_OF:Family"}}]}}}';
```
Yields: 
``` json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_not_found_exception",
        "reason" : "no such index [semmeddb]",
        "resource.type" : "index_or_alias",
        "resource.id" : "semmeddb",
        "index_uuid" : "_na_",
        "index" : "semmeddb"
      }
    ],
    "type" : "index_not_found_exception",
    "reason" : "no such index [semmeddb]",
    "resource.type" : "index_or_alias",
    "resource.id" : "semmeddb",
    "index_uuid" : "_na_",
    "index" : "semmeddb"
  },
  "status" : 404
}
```

**Comment by elswob** [comment]
Hi, this may be an issue with change in Elasticsearch syntax from v6 to v7. Could you try an older version of ES, e.g. 6.5?

**Comment by wrosko** [comment]
Good call, so far things are working. I forked and will make a PR with a couple changes, will just make sure that the whole creation process runs first.

**Comment by wrosko** [comment]
If you're curious: https://github.com/wrosko/MELODI-Presto/tree/local_initiation_updates/create

I can't run the frequency counts script prior to initiating the indices, so I moved it's order in the `.md` file. Is that reasonable?

**Comment by wrosko** [comment]
@elswob 2 questions for you 
1) In what order should the frequency count generation script be run? Running it first doesn't work cause there's nothing in the database. 
2) what size machine and/or cluster is needed for index creation. Loading the sentences into memory with pandas looks like it exceeds 120GB RAM, so I've been using `vaex` but it seems quite a bit slower than what you've said the times are. I assume this is because I'm lacking a kubernetes cluster since I'm running a single node?

**Comment by elswob** [comment]
Hi. Yeah, sorry, looks like the order is wrong. Maybe try this:

```
python -m create.index_semmeddb_predicate
python -m create.index_semmeddb_sentences
python -m create.create_semmed_freqs
python -m create.index_semmeddb_freqs
python -m create.index_semmeddb_citations
```

As for memory, I don't recall it being a problem, but pandas is probably not the best for this. Could it be the low_memory flag, e.g. `https://github.com/MRCIEU/MELODI-Presto/blob/main/create/index_semmeddb_sentences.py#L96`  ?

**Comment by wrosko** [comment]
Cool will try the freqs after sentences.

Yeah, the low_memory flag could be the problem. Will dabble with it a little. I appreciate the responsiveness!

**Comment by wrosko** [comment]
Hmm still getting an error, where is `aggregations` being created?

```shell
~/projects/MELODI-Presto$ python -m create.create_semmed_freqs
Creating counts for  semmeddb_triple
Running initial aggregation SUB_PRED_OBJ
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/projects/MELODI-Presto/create/create_semmed_freqs.py", line 119, in <module>
    create_counts("semmeddb_triple")
  File "/home/ubuntu/projects/MELODI-Presto/create/create_semmed_freqs.py", line 71, in create_counts
    for r in res["aggregations"]["my_buckets"]["buckets"]:
KeyError: 'aggregations'
```

**Comment by elswob** [comment]
Can you check to see if any data is in that index `semmeddb_triple` ?

**Comment by wrosko** [comment]
It is not:

```
predicate_frequency_index
predicate_index
sentence_index
```

frequency_index is there after just trying the freq index creation even though frequency creation didn't work.

**Comment by elswob** [comment]
Hmm, so there should be four indexes total, specified by the following names in `config.py`

```
semmed_predicate_index = '' # name of predicate index
semmed_sentence_index = '' # name of sentence index
semmed_citation_index = '' # name of citation index
semmed_triple_freqs_index = '' # name predicate frequency index
```
The index defined by `semmed_predicate_index` should be created before the frequency index `semmed_triple_freqs_index`

Does the predicate index contain data?  e.g. does `python -m create.index_semmeddb_predicate` add data to the index?

**Comment by wrosko** [comment]
I run:
``` shell
python -m create.index_semmeddb_predicate
python -m create.index_semmeddb_sentences
```

And have however million indices present.

Then I run 
``` shell
python -m create.create_semmed_freqs
```
and just get this error https://github.com/MRCIEU/MELODI-Presto/issues/4#issuecomment-1033133155

Can't figure it out because `aggregations` is only used/referenced in https://github.com/MRCIEU/MELODI-Presto/blob/main/create/create_semmed_freqs.py and there is no record of it being created anywhere. 

Is it related to these lines/do they need to be run separately? https://github.com/MRCIEU/MELODI-Presto/blob/122af3f22ccf9f2c4a83fa6ad693cea29e55b2e6/create/create_semmed_freqs.py#L28 Assuming no because I get 404 errors and they reference `semmeddb` as the index (which also doesn't exist).

Or does this need to be run https://github.com/MRCIEU/MELODI-Presto/blob/122af3f22ccf9f2c4a83fa6ad693cea29e55b2e6/create/create_semmed_freqs.py#L120 `semmeddb_subject` or `semmeddb_object`?

Edit:

Digging into it more, I think I've found the problem. It looks like a versioning artifact

**Comment by elswob** [comment]
Hi,

The commented out lines don't need to be run. The initial aggregation step is handled in the code.

What happens if you look at the result, e.g. comment out this https://github.com/MRCIEU/MELODI-Presto/blob/main/create/create_semmed_freqs.py#L69

It might be an elastic syntax change in the resulting aggregation query?

**Comment by elswob** [comment]
Yeah, I think there were changes in v6, notably after 6.8. Mentioned here regarding upgrades - https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html

Maybe try an older version of elastic, e.g. 6.5?

**Comment by wrosko** [comment]
https://github.com/MRCIEU/MELODI-Presto/blob/122af3f22ccf9f2c4a83fa6ad693cea29e55b2e6/create/create_semmed_freqs.py#L13

this needs to be `10000` or less with latest version 6 elastic 🙃, will include in my PR 

Freqs are being created now. 

Will keep you posted on the outcomes. Also in my PR I'll try to add sped up versions for the creation files that maybe use `vaex`. If I can't get those working I'll at least add the the small things that we've identified



the line mentioned above apparently throws this:

```
{'error': {'root_cause': [{'type': 'too_many_buckets_exception',
    'reason': 'Trying to create too many buckets. Must be less than or equal to: [10000] but was [100000]. This limit can be set by changing the [search.max_buckets] cluster level setting.',
    'max_buckets': 10000}],
  'type': 'search_phase_execution_exception',
  'reason': 'all shards failed',
  'phase': 'query',
  'grouped': True,
  'failed_shards': [{'shard': 0,
    'index': 'predicate_index',
    'node': '1RpYqzjcSweLVR_lSkBKCg',
    'reason': {'type': 'too_many_buckets_exception',
     'reason': 'Trying to create too many buckets. Must be less than or equal to: [10000] but was [100000]. This limit can be set by changing the [search.max_buckets] cluster level setting.',
     'max_buckets': 10000}}]},
 'status': 503}
```

**Comment by elswob** [comment]
Hi @wrosko did this work?

**Comment by wrosko** [comment]
So sorry, I've been distracted with several things. Will try to get a PR out this week. Feel free to close the issue

**Comment by elswob** [comment]
No problem at all, just checking :)
